/*
 * default_binds.h - the built-in bind DSL, written to
 * ~/.config/kalin-wm/binds.conf on first run and used as the fallback if a
 * user's file fails to parse. Reproduces the previous compiled keys[]/buttons[]
 * so upgrading keeps full parity. Kept in a shared header so the parser unit
 * test can verify the whole thing parses (guarding against drift).
 */
#ifndef KALIN_DEFAULT_BINDS_H
#define KALIN_DEFAULT_BINDS_H

static const char DEFAULT_BINDS[] =
"# kalin-wm bindings. Reloaded live when saved.\n"
"# Syntax: bind [tap|hold] Mods+Key -> action args    (# starts a comment)\n"
"# Mods: Super Shift Ctrl Alt.  See docs for the full grammar.\n"
"\n"
"bind Super+p       -> spawn fuzzel\n"
"bind Super+t       -> spawn foot\n"
"bind Super+o       -> spawn qs ipc call windows-bar toggleOverview\n"
"bind Super+Print   -> screenshot\n"
"bind Super+j       -> focus-stack next\n"
"bind Super+k       -> focus-stack prev\n"
"bind Super+Return  -> master-zoom\n"
"bind Super+q       -> close\n"
"bind Super+c       -> crop\n"
"bind Super+Shift+r -> crop-cancel\n"
"bind Super+i       -> layout infinite\n"
"bind Super+f       -> layout floating\n"
"bind Super+space   -> layout toggle\n"
"bind Super+Shift+space -> toggle-floating\n"
"bind Super+e       -> toggle-fullscreen\n"
"bind Super+d       -> opacity -0.1\n"
"bind Super+Shift+d -> opacity 0.1\n"
"bind Super+comma   -> focus-monitor left\n"
"bind Super+period  -> focus-monitor right\n"
"bind Super+Shift+less    -> move-monitor left\n"
"bind Super+Shift+greater -> move-monitor right\n"
"bind Super+Escape  -> quit\n"
"\n"
"# Tap Super (quick press+release) toggles the app launcher.\n"
"bind tap Super -> toggle-launcher fuzzel\n"
"# Hold Super for 1s (uninterrupted by another key) to show the window menu.\n"
"bind hold Super -> window-menu\n"
"\n"
"# Camera pan (arrows + vim keys)\n"
"bind Super+Shift+Left  -> viewport.pan -50 0\n"
"bind Super+Shift+Right -> viewport.pan 50 0\n"
"bind Super+Shift+Up    -> viewport.pan 0 -50\n"
"bind Super+Shift+Down  -> viewport.pan 0 50\n"
"bind Super+Shift+h -> viewport.pan -50 0\n"
"bind Super+Shift+l -> viewport.pan 50 0\n"
"bind Super+Shift+k -> viewport.pan 0 -50\n"
"bind Super+Shift+j -> viewport.pan 0 50\n"
"bind Super+Ctrl+equal -> viewport.zoom 1.1\n"
"bind Super+Ctrl+minus -> viewport.zoom 0.9\n"
"bind Super+0         -> viewport.fit\n"
"bind Super+BackSpace -> viewport.reset\n"
"bind Super+z         -> viewport.follow\n"
"bind Super+Shift+z   -> viewport.follow-new\n"
"\n"
"# Move focused window between columns (Niri-style)\n"
"bind Ctrl+Left  -> move-column left\n"
"bind Ctrl+Right -> move-column right\n"
"\n"
"# Directional focus\n"
"bind Super+Left  -> focus left\n"
"bind Super+Right -> focus right\n"
"bind Super+Up    -> focus up\n"
"bind Super+Down  -> focus down\n"
"\n"
"# Carry the focused window through the grid (swap; up-at-top consumes left)\n"
"bind Super+Ctrl+Left  -> move-window left\n"
"bind Super+Ctrl+Right -> move-window right\n"
"bind Super+Ctrl+Up    -> move-window up\n"
"bind Super+Ctrl+Down  -> move-window down\n"
"\n"
"# Resize focused window: Super+=/- width, Super+Shift+=/- (plus/underscore) height\n"
"bind Super+equal  -> resize width 40\n"
"bind Super+minus  -> resize width -40\n"
"bind Super+Shift+plus       -> resize height 40\n"
"bind Super+Shift+underscore -> resize height -40\n"
"bind Super+bracketleft  -> resize width -40\n"
"bind Super+bracketright -> resize width 40\n"
"bind Super+Shift+braceleft  -> resize height -40\n"
"bind Super+Shift+braceright -> resize height 40\n"
"\n"
"# Pointer (drag to move/resize the focused window)\n"
"bind Super+BTN_LEFT       -> pointer-move\n"
"bind Super+BTN_MIDDLE     -> toggle-floating\n"
"bind Super+BTN_RIGHT      -> pointer-resize\n"
"bind Super+Ctrl+BTN_RIGHT -> pointer-resize\n"
"\n"
"# VT switching / emergency quit (do not remove)\n"
"bind Ctrl+Alt+Terminate_Server -> quit\n"
"bind Ctrl+Alt+XF86Switch_VT_1  -> chvt 1\n"
"bind Ctrl+Alt+XF86Switch_VT_2  -> chvt 2\n"
"bind Ctrl+Alt+XF86Switch_VT_3  -> chvt 3\n"
"bind Ctrl+Alt+XF86Switch_VT_4  -> chvt 4\n"
"bind Ctrl+Alt+XF86Switch_VT_5  -> chvt 5\n"
"bind Ctrl+Alt+XF86Switch_VT_6  -> chvt 6\n"
"bind Ctrl+Alt+XF86Switch_VT_7  -> chvt 7\n"
"bind Ctrl+Alt+XF86Switch_VT_8  -> chvt 8\n"
"bind Ctrl+Alt+XF86Switch_VT_9  -> chvt 9\n"
"bind Ctrl+Alt+XF86Switch_VT_10 -> chvt 10\n"
"bind Ctrl+Alt+XF86Switch_VT_11 -> chvt 11\n"
"bind Ctrl+Alt+XF86Switch_VT_12 -> chvt 12\n";

#endif /* KALIN_DEFAULT_BINDS_H */
